-- Deprecated: PK Bot identities are system profiles in pk_bot_profiles and must
-- never create rows in users. Profile seeds are created by migration 0083.
-- Kept as an intentionally empty migration for installations that already
-- recorded migration 0081 in their migration ledger.
