"use client";
import { useEffect, useMemo, useState } from "react";
import { Button, Card, Field, Select, Stat } from "@/components/ui";
const DATASETS = [{ key: "notes", label: "我的專屬筆記", group: "學習資料" }, { key: "vocabulary", label: "單字", group: "學習資料" }, { key: "wrong", label: "錯題本", group: "測驗資料" }, { key: "studyMaterials", label: "AI 整理與學習資料", group: "學習資料" }, { key: "plans", label: "學習計畫", group: "學習紀錄" }, { key: "studyRecords", label: "每日學習紀錄", group: "學習紀錄" }, { key: "focus", label: "專注計時", group: "學習紀錄" }, { key: "tasks", label: "任務紀錄", group: "學習紀錄" }, { key: "dailyTasks", label: "每日任務", group: "學習紀錄" }, { key: "achievements", label: "成就與徽章", group: "學習紀錄" }, { key: "nova", label: "Nova 交易紀錄", group: "帳務紀錄" }, { key: "xp", label: "XP 紀錄", group: "帳務紀錄" }];
const FORMATS = [{ key: "json", label: "JSON（完整結構）" }, { key: "csv", label: "CSV（表格）" }, { key: "xlsx", label: "XLSX（Excel）" }, { key: "txt", label: "TXT（純文字）" }, { key: "md", label: "Markdown" }, { key: "pdf", label: "PDF（學習報告）" }, { key: "docx", label: "DOCX（Word）" }, { key: "zip", label: "ZIP（完整資料）" }];
export default function ExportPage() {
  const [selected, setSelected] = useState<string[]>(["notes"]); const [format, setFormat] = useState("json"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [preview, setPreview] = useState<{ datasets: Array<{ label: string; count: number }>; total: number; estimatedBytes: number; noCharge: boolean } | null>(null); const [loading, setLoading] = useState(false);
  const query = useMemo(() => `/api/v1/exports/preview?kind=${encodeURIComponent(selected.join(","))}${from ? `&from=${encodeURIComponent(new Date(from).toISOString())}` : ""}${to ? `&to=${encodeURIComponent(new Date(to).toISOString())}` : ""}`, [selected, from, to]);
  useEffect(() => { if (!selected.length) return; const timer = window.setTimeout(() => { setLoading(true); fetch(query, { credentials: "include" }).then((r) => r.json()).then((r) => setPreview(r.data)).catch(() => setPreview(null)).finally(() => setLoading(false)); }, 250); return () => window.clearTimeout(timer); }, [query, selected.length]);
  const toggle = (key: string) => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]);
  const downloadUrl = selected.length ? `/api/v1/exports/download?kind=${encodeURIComponent(selected.join(","))}&format=${format}${from ? `&from=${encodeURIComponent(new Date(from).toISOString())}` : ""}${to ? `&to=${encodeURIComponent(new Date(to).toISOString())}` : ""}` : "#";
  return <main className="container space-y-5 py-6 sm:py-8"><div><p className="text-xs uppercase tracking-[.24em] text-[#37d3ff]">MY DATA</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">我的資料匯出中心</h1><p className="mt-2 max-w-3xl text-sm text-muted">我的學習資料，我可以隨時帶走。所有查詢都由後端依目前登入帳號限制，只會匯出你自己的資料；預覽不扣 Nova、不消耗免費次數。</p></div><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card title="選擇資料" subtitle="可複選多種資料，系統只會顯示資料庫中實際存在的紀錄"><div className="grid gap-2 sm:grid-cols-2">{DATASETS.map((item) => <label key={item.key} className={`flex cursor-pointer items-center gap-2 rounded-xl border p-3 text-sm transition ${selected.includes(item.key) ? "border-[#37d3ff]/60 bg-[#37d3ff]/10" : "border-[var(--line)] bg-white/[0.02]"}`}><input type="checkbox" checked={selected.includes(item.key)} onChange={() => toggle(item.key)} className="accent-[#37d3ff]" /><span><strong>{item.label}</strong><small className="mt-0.5 block text-[10px] text-muted">{item.group}</small></span></label>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="開始日期" hint="留空代表不限"><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2" /></Field><Field label="結束日期" hint="留空代表不限"><input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2" /></Field></div></Card><Card title="格式與匯出" subtitle="先確認預覽，再下載正式檔案"><Field label="匯出格式"><Select value={format} onChange={(e) => setFormat(e.target.value)}>{FORMATS.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</Select></Field>{preview && <div className="mt-4 grid grid-cols-2 gap-2"><Stat label="資料筆數" value={preview.total} tone="cyan" /><Stat label="預估大小" value={`${(preview.estimatedBytes / 1024).toFixed(1)} KB`} /></div>}<div className="mt-4 rounded-xl border border-[#37d3ff]/20 bg-[#37d3ff]/5 p-3 text-xs leading-5 text-muted">{loading ? "正在建立預覽…" : preview ? `包含 ${preview.datasets.filter((item) => item.count > 0).map((item) => `${item.label} ${item.count} 筆`).join("、") || "目前沒有符合條件的資料"}。` : "選擇資料後會顯示預計筆數與大小。"}</div>{selected.length > 0 && preview?.total ? <a href={downloadUrl} className="mt-4 block"><Button full variant="gold">確認並下載 {format.toUpperCase()}</Button></a> : <Button full disabled>沒有可匯出的資料</Button>}</Card></div><Card title="匯出安全說明"><div className="grid gap-2 text-xs leading-5 text-muted sm:grid-cols-3"><p>只查詢目前登入使用者的資料，不接受前端傳入 userId。</p><p>JSON、CSV、XLSX、TXT、Markdown、PDF、DOCX 與 ZIP 都由後端產生。</p><p>AI 對話等資料不包含 System Prompt、API Key、Token 或內部工具資訊。</p></div></Card></main>;
}
