"use client";

import { useEffect, useMemo, useState } from "react";
import { Button, Card, Field, Select, Stat } from "@/components/ui";

const DATASETS = [
  { key: "notes", label: "我的專屬筆記", group: "學習資料" }, { key: "vocabulary", label: "我的單字", group: "學習資料" }, { key: "wrong", label: "錯題本", group: "測驗資料" }, { key: "studyMaterials", label: "AI 整理與學習資料", group: "學習資料" }, { key: "plans", label: "學習計畫", group: "學習紀錄" }, { key: "studyRecords", label: "每日學習紀錄", group: "學習紀錄" }, { key: "focus", label: "專注計時", group: "學習紀錄" }, { key: "tasks", label: "任務紀錄", group: "學習紀錄" }, { key: "dailyTasks", label: "每日任務", group: "學習紀錄" }, { key: "achievements", label: "成就與徽章", group: "學習紀錄" }, { key: "nova", label: "Nova 交易紀錄", group: "帳務紀錄" }, { key: "xp", label: "XP 紀錄", group: "帳務紀錄" },
];
const FORMAT_LABELS: Record<string, string> = { json: "JSON", csv: "CSV（單字表格）", xlsx: "XLSX（Excel 單字書）", txt: "TXT（單字清單）", md: "Markdown", pdf: "PDF（單字書／學習報告）", docx: "DOCX（Word 單字書）", zip: "ZIP（完整資料）" };
type Policy = { enabled: boolean; proOnly: boolean; isPro: boolean; allowedKinds: string[]; allowedFormats: string[]; freeFormats: string[]; freeUntil: string | null; costs: Record<string, number> };
type Preview = { datasets: Array<{ label: string; count: number }>; total: number; estimatedBytes: number; sample: Array<Record<string, unknown>>; cost: number; free?: boolean };
type Artifact = { kind: "text" | "pdf" | "other"; value: string };

export default function ExportPage() {
  const [policy, setPolicy] = useState<Policy | null>(null); const [selected, setSelected] = useState<string[]>(["vocabulary"]); const [format, setFormat] = useState("pdf"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [preview, setPreview] = useState<Preview | null>(null); const [loading, setLoading] = useState(false); const [policyLoading, setPolicyLoading] = useState(true); const [error, setError] = useState(""); const [artifact, setArtifact] = useState<Artifact | null>(null); const [artifactLoading, setArtifactLoading] = useState(false); const [now, setNow] = useState<number | null>(null);
  useEffect(() => { fetch("/api/v1/exports/policy", { credentials: "include" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message ?? "無法讀取匯出政策"); return body.data; }).then((value: Policy) => { setPolicy(value); const queryDataset = new URLSearchParams(window.location.search).get("dataset"); const firstKind = queryDataset && value.allowedKinds.includes(queryDataset) ? queryDataset : value.allowedKinds.includes("vocabulary") ? "vocabulary" : value.allowedKinds[0]; if (firstKind) setSelected([firstKind]); const firstFormat = value.allowedFormats.includes("pdf") ? "pdf" : value.allowedFormats[0]; if (firstFormat) setFormat(firstFormat); }).catch((err) => setError(err instanceof Error ? err.message : "無法讀取匯出政策")).finally(() => setPolicyLoading(false)); }, []);
  useEffect(() => { const timer = window.setTimeout(() => setNow(Date.now()), 0); return () => window.clearTimeout(timer); }, []);
  const visibleDatasets = DATASETS.filter((item) => policy?.allowedKinds.includes(item.key)); const freeActive = !policy?.freeUntil || (now !== null && new Date(policy.freeUntil).getTime() > now); const visibleFormats = (policy?.allowedFormats ?? []).map((key) => ({ key, label: FORMAT_LABELS[key] ?? key, cost: policy?.freeFormats.includes(key) && freeActive ? 0 : policy?.costs[key] ?? 0 }));
  const query = useMemo(() => `/api/v1/exports/preview?kind=${encodeURIComponent(selected.join(","))}&format=${format}${from ? `&from=${encodeURIComponent(new Date(from).toISOString())}` : ""}${to ? `&to=${encodeURIComponent(new Date(to).toISOString())}` : ""}`, [selected, format, from, to]);
  const formatCost = visibleFormats.find((item) => item.key === format)?.cost ?? 0; const totalCost = preview?.cost ?? formatCost;
  useEffect(() => { if (!policy || !selected.length || !policy.allowedFormats.includes(format)) return; const timer = window.setTimeout(() => { setLoading(true); setError(""); fetch(query, { credentials: "include" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message ?? "無法建立匯出預覽"); return body.data; }).then((value: Preview) => setPreview(value)).catch((err) => { setPreview(null); setError(err instanceof Error ? err.message : "無法建立匯出預覽"); }).finally(() => setLoading(false)); }, 250); return () => window.clearTimeout(timer); }, [policy, query, selected.length, format]);
  useEffect(() => { if (!policy || !selected.length || !preview) { const clearTimer = window.setTimeout(() => setArtifact(null), 0); return () => window.clearTimeout(clearTimer); } let active = true; let objectUrl = ""; const timer = window.setTimeout(async () => { setArtifact(null); setArtifactLoading(true); try { const response = await fetch(query.replace("/exports/preview?", "/exports/preview-file?"), { credentials: "include" }); if (!response.ok) throw new Error("無法產生成品預覽"); const type = response.headers.get("content-type") ?? ""; if (type.includes("application/pdf")) { objectUrl = URL.createObjectURL(await response.blob()); if (active) setArtifact({ kind: "pdf", value: objectUrl }); } else if (type.includes("text/") || type.includes("json") || type.includes("csv")) { if (active) setArtifact({ kind: "text", value: await response.text() }); } else if (active) setArtifact({ kind: "other", value: "此格式已產生成品，正式生成後可下載檔案。" }); } catch { if (active) setArtifact(null); } finally { if (active) setArtifactLoading(false); } }, 250); return () => { active = false; window.clearTimeout(timer); if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [query, selected.length, preview, policy]);
  const toggle = (key: string) => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]);
  const downloadUrl = selected.length ? `/api/v1/exports/download?kind=${encodeURIComponent(selected.join(","))}&format=${format}&confirmed=1${from ? `&from=${encodeURIComponent(new Date(from).toISOString())}` : ""}${to ? `&to=${encodeURIComponent(new Date(to).toISOString())}` : ""}` : "#";
  const download = () => { if (!preview || loading || !selected.length) return; if (!window.confirm(totalCost ? `將生成 ${format.toUpperCase()}，總共扣除 ${totalCost} Nova。確定繼續嗎？` : `將免費生成 ${format.toUpperCase()}。確定繼續嗎？`)) return; window.location.assign(downloadUrl); };
  return <main className="container space-y-5 py-6 sm:py-8"><div><p className="text-xs uppercase tracking-[.24em] text-[#37d3ff]">MY DATA</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">我的資料匯出中心</h1><p className="mt-2 max-w-3xl text-sm text-muted">先預覽真正會生成的成品，再選擇資料與格式。單字 PDF、Word、Excel 會以單字書格式輸出，不會顯示資料庫 JSON。</p></div>
    {policy?.proOnly && !policy.isPro && <Card><p className="text-sm text-[#ffd98a]">目前匯出功能僅開放 Nova Pro；請升級 Pro 後再使用。</p></Card>}
    {error && <Card><p className="text-sm text-rose-200">{error}</p></Card>}
    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card title="選擇資料" subtitle="可複選已開放的資料類型，僅能匯出目前登入帳號自己的紀錄"><div className="grid gap-2 sm:grid-cols-2">{visibleDatasets.map((item) => <label key={item.key} className={`flex cursor-pointer items-center gap-2 rounded-xl border p-3 text-sm transition ${selected.includes(item.key) ? "border-[#37d3ff]/60 bg-[#37d3ff]/10" : "border-[var(--line)] bg-white/[0.02]"}`}><input type="checkbox" checked={selected.includes(item.key)} onChange={() => toggle(item.key)} className="accent-[#37d3ff]" /><span><strong>{item.label}</strong><small className="mt-0.5 block text-[10px] text-muted">{item.group}</small></span></label>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="開始日期" hint="留空代表不限"><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2" /></Field><Field label="結束日期" hint="留空代表不限"><input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2" /></Field></div></Card>
      <Card title="格式與生成" subtitle="費用與免費規則由後台控制"><Field label="匯出格式"><Select value={format} onChange={(event) => setFormat(event.target.value)} disabled={policyLoading}>{visibleFormats.map((item) => <option key={item.key} value={item.key}>{item.label}・{item.cost ? `${item.cost} Nova` : "限時免費"}</option>)}</Select></Field>{preview && <div className="mt-4 grid grid-cols-2 gap-2"><Stat label="資料筆數" value={preview.total} tone="cyan" /><Stat label="預估大小" value={`${(preview.estimatedBytes / 1024).toFixed(1)} KB`} /></div>}<div className="mt-4 min-h-12 rounded-xl border border-[#37d3ff]/20 bg-[#37d3ff]/5 p-3 text-xs leading-5 text-muted">{preview ? `包含 ${preview.datasets.filter((item) => item.count > 0).map((item) => `${item.label} ${item.count} 筆`).join("、") || "目前沒有符合條件的資料"}。${preview.free ? "本格式目前由後台設定為限時免費。" : `生成費用：${totalCost} Nova。`}` : "選擇資料後會顯示預計筆數、大小與實際成品。"}</div><Button full variant="gold" onClick={download} disabled={!preview || loading || !selected.length || (policy?.proOnly === true && policy.isPro === false)}>生成匯出（{totalCost ? `扣 ${totalCost} Nova` : "免費"}）</Button></Card></div>
    <Card title={`實際成品預覽：${(FORMAT_LABELS[format] ?? format).toUpperCase()}`} subtitle="預覽與正式下載使用同一套生成器；PDF／DOCX／XLSX 會使用清楚的單字書欄位。">{artifactLoading && <div className="h-24 animate-pulse rounded-xl bg-white/5" aria-label="預覽準備中" />}{!artifactLoading && artifact?.kind === "pdf" && <iframe title="PDF 匯出成品預覽" src={artifact.value} className="h-[680px] w-full rounded-xl border border-[var(--line)] bg-white" />}{!artifactLoading && artifact?.kind === "text" && <pre className="max-h-[520px] overflow-auto whitespace-pre-wrap rounded-xl border border-[var(--line)] bg-black/30 p-4 text-xs leading-5">{artifact.value}</pre>}{!artifactLoading && artifact?.kind === "other" && <div className="rounded-xl border border-[#ffc857]/30 bg-[#ffc857]/10 p-4 text-sm text-[#ffe7ad]">{artifact.value}</div>}{!artifactLoading && !artifact && <p className="text-xs text-muted">選擇資料後會顯示實際格式預覽。</p>}</Card>
    {preview?.sample?.length ? <Card title="資料內容摘要" subtitle="以下為部分資料，單字會顯示單字、詞性、音標、中文意思與例句"><div className="max-h-72 overflow-auto rounded-lg bg-black/20 p-3">{preview.sample.map((row, index) => <pre key={index} className="mb-3 whitespace-pre-wrap border-b border-[var(--line)] pb-2 text-xs last:mb-0 last:border-0">{JSON.stringify(row, null, 2)}</pre>)}</div></Card> : null}<Card title="匯出安全說明"><div className="grid gap-2 text-xs leading-5 text-muted sm:grid-cols-3"><p>預覽不扣 Nova；只有正式生成才會依後台規則扣點。</p><p>後台可控制資料類型、格式、各格式 Nova 價格與限時免費格式。</p><p>不會包含 System Prompt、API Key、Token 或內部工具資訊。</p></div></Card>
  </main>;
}
