"use client";
import { useState } from "react";
import { apiPost, errorMessage, useApi } from "@/lib/api";
import { Badge, Button, Card, EmptyState, Field, Input, Textarea, useToast } from "@/components/ui";

type Row = { request: { userId: string; wantsRenewal: boolean; reason: string; requestedFeatures: string[]; otherFeedback: string; submittedAt: string } | null; user: { userId: string; displayName: string; email: string }; membership: { tier: string; expiresAt: string | null } | null };
export default function AdminProRenewalsPage() {
  const toast = useToast(); const list = useApi<{ requests: Row[] }>("/admin/pro-renewals"); const [selected, setSelected] = useState<Row | null>(null); const [days, setDays] = useState("3"); const [reason, setReason] = useState("續約意願處理"); const [note, setNote] = useState(""); const [letter, setLetter] = useState(""); const [activation, setActivation] = useState<{ link: string; expiresAt: string; customerMessage: string } | null>(null);
  async function extend() { if (!selected) return; try { const result = await apiPost<{ customerLetter: string }>(`/admin/pro-renewals/${selected.user.userId}/extend`, { days: Number(days), reason, adminNote: note }); setLetter(result.customerLetter); toast.push("success", "Nova Pro 已由後端延長並寫入審計紀錄"); await list.reload(); } catch (err) { toast.push("error", errorMessage(err)); } }
  async function createLink() { if (!selected) return; try { const result = await apiPost<typeof activation>("/admin/pro-activation-links", { targetUserId: selected.user.userId, baseUrl: window.location.origin }); setActivation(result); toast.push("success", "已建立一小時有效的一次性連結"); } catch (err) { toast.push("error", errorMessage(err)); } }
  async function createLetter() { if (!selected) return; try { const result = await apiPost<{ customerLetter: string }>(`/admin/pro-renewals/${selected.user.userId}/customer-letter`); setLetter(result.customerLetter); toast.push("success", "客服信件草稿已產生"); } catch (err) { toast.push("error", errorMessage(err)); } }
  return <div className="space-y-4"><header><p className="text-xs uppercase tracking-[0.2em] text-[#ffc857]">Membership Operations</p><h1 className="mt-1 text-2xl font-semibold">Nova Pro 到期與續約</h1><p className="text-sm text-muted">管理員延長一定由後端執行，並記錄管理員、原到期日、新到期日、天數與原因。</p></header><Card title="學生會員清單"><div className="space-y-2">{list.loading && <p className="text-sm text-muted">載入中…</p>}{!list.loading && !list.data?.requests.length && <EmptyState title="尚無學生帳號" />}{list.data?.requests.map((row) => <button key={row.user.userId} type="button" onClick={() => setSelected(row)} className={`glass-soft flex w-full items-center justify-between gap-3 rounded-xl p-3 text-left ${selected?.user.userId === row.user.userId ? "border-[#ffc857]" : ""}`}><span><b>{row.user.displayName}</b><span className="ml-2 text-xs text-muted">{row.user.email}</span><span className="mt-1 block text-xs text-muted">到期：{row.membership?.expiresAt ? new Date(row.membership.expiresAt).toLocaleString("zh-TW") : "無"}・{row.request ? `提交：${new Date(row.request.submittedAt).toLocaleString("zh-TW")}` : "尚未提交續約意願"}</span></span><Badge tone={row.request?.wantsRenewal ? "gold" : "muted"}>{row.request?.wantsRenewal ? "想續約" : "未提交／暫不續約"}</Badge></button>)}</div></Card>{selected && <Card title={`處理：${selected.user.displayName}`} subtitle={`原因：${selected.request?.reason || "未提供"}；功能：${selected.request?.requestedFeatures.join("、") || "未提供"}`}><div className="grid gap-3 sm:grid-cols-3"><Field label="延長天數"><Input type="number" min={1} max={365} value={days} onChange={(e) => setDays(e.target.value)} /></Field><Field label="操作原因"><Input value={reason} onChange={(e) => setReason(e.target.value)} /></Field><Field label="管理員備註"><Input value={note} onChange={(e) => setNote(e.target.value)} /></Field></div><div className="mt-3 flex flex-wrap gap-2"><Button onClick={() => void extend()}>後端延長 Nova Pro</Button><Button variant="outline" onClick={() => void createLetter()}>產生客服信件</Button><Button variant="outline" onClick={() => void createLink()}>建立 3 天一次性連結</Button></div>{letter && <div className="mt-4"><p className="mb-1 text-sm font-semibold">客服信件草稿（不會自動寄出）</p><Textarea className="min-h-[180px]" value={letter} readOnly /><Button size="sm" variant="ghost" className="mt-2" onClick={() => navigator.clipboard.writeText(letter)}>複製客服信件</Button></div>}{activation && <div className="mt-4 space-y-2 rounded-xl border border-[#ffc857]/30 bg-[#ffc857]/5 p-3"><p className="text-sm font-semibold">一次性啟用連結</p><Input readOnly value={activation.link} /><p className="text-xs text-muted">有效期限：{new Date(activation.expiresAt).toLocaleString("zh-TW")}；使用後立即失效。</p><Button size="sm" variant="ghost" onClick={() => navigator.clipboard.writeText(activation.link)}>複製連結</Button><Textarea className="min-h-[100px]" value={activation.customerMessage} readOnly /></div>}</Card>}</div>;
}
