"use client";
import { useState } from "react";
import { Badge, Button, Card, EmptyState, ErrorState, Input, Select, Skeleton } from "@/components/ui";
import { useApi } from "@/lib/api";
type Log = { id: string; userId: string | null; userName: string | null; userNovaId: string | null; occurredAt: string; eventType: string; module: string; action: string; resourceId: string; outcome: string; errorCategory: string; correlationId: string; ip: string; metadata: Record<string, unknown> };
type Summary = { date: string; totals: { total: number; success: number; failure: number }; byAction: Array<{ action: string; count: number }>; byUser: Array<{ userId: string | null; userName: string | null; userNovaId: string | null; count: number; lastActiveAt: string }> };
export default function AuditPage() {
  const [q, setQ] = useState(""); const [userId, setUserId] = useState(""); const [outcome, setOutcome] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1);
  const params = `/admin/audit-logs?page=${page}&q=${encodeURIComponent(q)}&userId=${encodeURIComponent(userId)}&outcome=${outcome}&from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`;
  const logs = useApi<{ logs: Log[]; total: number; totalPages: number }>(params, [page, q, userId, outcome, from, to]);
  const summary = useApi<Summary>("/admin/audit-summary", []);
  return <div className="space-y-4"><div className="anim-in"><p className="text-xs uppercase tracking-[0.2em] text-[#37d3ff]">Control Center / Diagnostics</p><h1 className="mt-1 text-2xl font-semibold">使用者操作紀錄</h1><p className="text-sm text-muted">每筆紀錄包含發生時間、使用者名稱、Nova ID 與操作結果；統計區顯示今日使用次數。</p></div>
    <div className="grid gap-3 sm:grid-cols-3"><Card title="今日總次數"><p className="text-3xl font-black text-[#37d3ff]">{summary.data?.totals.total ?? "—"}</p></Card><Card title="成功次數"><p className="text-3xl font-black text-emerald-300">{summary.data?.totals.success ?? "—"}</p></Card><Card title="失敗次數"><p className="text-3xl font-black text-rose-300">{summary.data?.totals.failure ?? "—"}</p></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card title={`今日熱門功能（${summary.data?.date ?? "—"}）`} action={<Button size="sm" variant="ghost" onClick={summary.reload}>重新整理</Button>}><div className="space-y-2">{summary.data?.byAction.slice(0, 8).map(item => <div key={item.action} className="flex items-center justify-between rounded-lg bg-white/5 px-3 py-2 text-sm"><span>{item.action}</span><b>{item.count} 次</b></div>)}{!summary.loading && !summary.data?.byAction.length && <EmptyState icon="▤" title="今日尚無操作紀錄" />}</div></Card><Card title="今日使用者次數"><div className="space-y-2">{summary.data?.byUser.slice(0, 8).map(item => <div key={item.userId ?? "system"} className="flex items-center justify-between rounded-lg bg-white/5 px-3 py-2 text-sm"><span><b>{item.userName ?? "系統／排程"}</b><small className="ml-2 text-muted">{item.userNovaId ?? "—"}</small></span><b>{item.count} 次</b></div>)}{!summary.loading && !summary.data?.byUser.length && <EmptyState icon="▤" title="今日尚無使用者紀錄" />}</div></Card></div>
    <Card title="搜尋條件"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Input placeholder="操作、Resource ID、錯誤分類" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><Input placeholder="User ID" value={userId} onChange={e=>{setUserId(e.target.value);setPage(1)}}/><Select value={outcome} onChange={e=>{setOutcome(e.target.value);setPage(1)}}><option value="">全部結果</option><option value="success">成功</option><option value="failure">失敗</option></Select><Input type="datetime-local" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/><Input type="datetime-local" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/><Button onClick={()=>void logs.reload()}>重新整理</Button></div></Card>{logs.loading&&<Card><Skeleton lines={7}/></Card>}{logs.error&&<ErrorState message={logs.error} onRetry={logs.reload}/>}<Card title={logs.data?`共 ${logs.data.total} 筆・第 ${page}/${Math.max(1,logs.data.totalPages)} 頁`:"Audit timeline"}><div className="space-y-2">{logs.data?.logs.map(l=><details key={l.id} className="glass-soft p-3 text-xs"><summary className="flex cursor-pointer flex-wrap items-center justify-between gap-2"><span className="flex items-center gap-2"><Badge tone={l.outcome==='success'?'green':'rose'}>{l.outcome}</Badge><b>{l.action}</b><span className="text-muted">{l.module}</span></span><time className="text-muted">{new Date(l.occurredAt).toLocaleString('zh-TW')}</time></summary><div className="mt-3 grid gap-1 text-muted sm:grid-cols-2"><span>使用者：<b>{l.userName??'系統／排程'}</b></span><span>Nova ID：<code>{l.userNovaId??'—'}</code></span><span>User ID：<code>{l.userId??'—'}</code></span><span>Resource：<code>{l.resourceId||'—'}</code></span><span>Correlation：<code>{l.correlationId}</code></span><span>Error：{l.errorCategory||'—'}</span><span>IP：{l.ip||'—'}</span></div></details>)}{!logs.loading&&!logs.data?.logs.length&&<EmptyState icon="▤" title="沒有符合條件的紀錄"/>}</div><div className="mt-4 flex justify-between"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>上一頁</Button><Button size="sm" variant="outline" disabled={!logs.data||page>=logs.data.totalPages} onClick={()=>setPage(p=>p+1)}>下一頁</Button></div></Card></div>;
}
