"use client";
import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { apiGet, apiPost, errorMessage } from "@/lib/api";
import { Badge, Button, Card, Field, Input, Select, Stat, useToast } from "@/components/ui";
import { BarChart, LineChart } from "@/components/charts";

type Job = { id: string; originalFilename: string; mimeType: string; outputFormat?: string; originalSize: number; targetSize: number; status: string; stage: string; compressedSize: number | null; compressionRatio: number | null; qualityScore: string | null; errorMessage: string; resultUrl: string | null; progress: number; preview: Record<string, unknown> };
type Batch = { batchId: string; batchName: string; total: number; completed: number; failed: number; progress: number; zipUrl: string | null; jobs: Job[] };
const pretty = (bytes: number | null) => bytes == null ? "—" : bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(2)} MB` : `${(bytes / 1024).toFixed(1)} KB`;
const stageText: Record<string, string> = { QUEUED: "排隊中", ANALYZING: "分析", COMPRESSING: "最佳化", VERIFYING: "驗證", COMPLETED: "完成", FAILED: "失敗" };

export default function CompressPage() {
  const toast = useToast();
  const [files, setFiles] = useState<File[]>([]);
  const [target, setTarget] = useState("5");
  const [unit, setUnit] = useState("MB");
  const [mode, setMode] = useState("precise");
  const [outputFormat, setOutputFormat] = useState("original");
  const [job, setJob] = useState<Job | null>(null);
  const [batch, setBatch] = useState<Batch | null>(null);
  const [history, setHistory] = useState<Job[]>([]);
  const [filter, setFilter] = useState("all");
  const [stats, setStats] = useState<{ totalJobs: number; completedJobs: number; totalOriginalBytes: number; totalCompressedBytes: number; averageSavedPercent: number; daily: Array<{ label: string; value: number; saved: number }> } | null>(null);
  const [busy, setBusy] = useState(false);
  const refresh = async () => { try { const data = await apiGet<{ jobs: Job[] }>("/compress/jobs"); setHistory(data.jobs); } catch { /* auth shell handles session */ } };
  useEffect(() => { const timer = window.setTimeout(() => { void refresh(); void apiGet<typeof stats>("/compress/stats?days=30").then(setStats).catch(() => {}); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => {
    if (!job || ["completed", "completed_with_warning", "failed"].includes(job.status)) return;
    const timer = window.setInterval(async () => { try { const next = await apiGet<Job>(`/compress/jobs/${job.id}`); setJob(next); if (["completed", "completed_with_warning", "failed"].includes(next.status)) { await refresh(); } } catch { /* keep polling */ } }, 1600);
    return () => window.clearInterval(timer);
  }, [job]);
  useEffect(() => { if (!batch || batch.progress >= 100) return; const timer = window.setInterval(async () => { try { const next = await apiGet<Batch>(`/compress/batches/${batch.batchId}`); setBatch(next); if (next.progress >= 100) { await refresh(); const s = await apiGet<typeof stats>("/compress/stats?days=30"); setStats(s); } } catch { /* keep polling */ } }, 1800); return () => window.clearInterval(timer); }, [batch]);
  const warning = useMemo(() => files.some((file) => Number(target) * (unit === "MB" ? 1024 * 1024 : 1024) < 1024 * 1024 && file.type.startsWith("image/")), [files, target, unit]);
  const visibleHistory = history.filter((item) => filter === "all" || (filter === "completed" ? item.status.includes("completed") : item.status === filter));
  async function submit() {
    if (!files.length) { toast.push("error", "請先選擇檔案"); return; }
    setBusy(true);
    try { const form = new FormData(); files.forEach((file) => form.append(files.length > 1 ? "files" : "file", file)); form.set("targetSize", target); form.set("targetUnit", unit); form.set("mode", mode); form.set("outputFormat", outputFormat); if (files.length > 1) { const data = await apiPost<Batch>("/compress/batches", form); setBatch(data); toast.push("success", `已建立 ${files.length} 個檔案的批次壓縮`); } else { const data = await apiPost<{ job: Job }>("/compress/jobs", form); setJob(data.job); toast.push("success", "壓縮工作已建立"); } } catch (err) { toast.push("error", errorMessage(err)); } finally { setBusy(false); }
  }
  return <main className="container space-y-5 py-6 sm:py-8">
    <div><p className="text-xs uppercase tracking-[.24em] text-[#37d3ff]">SMART COMPRESSOR</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">智慧檔案壓縮中心</h1><p className="mt-2 max-w-2xl text-sm text-muted">輸入目標檔案大小，系統會以目標大小導向策略自動調整品質、解析度與編碼；如果安全品質下無法達成，會誠實告知最佳結果。</p></div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <Card title="開始智慧壓縮" subtitle="支援 JPG、PNG、WebP、AVIF 與 PDF；可一次選取多個檔案並打包 ZIP">
        <label className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-[#37d3ff]/40 bg-[#37d3ff]/5 p-5 text-center hover:bg-[#37d3ff]/10"><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif,application/pdf" className="sr-only" onChange={(e) => setFiles(Array.from(e.target.files ?? []))} /><span className="text-3xl">⇧</span><strong className="mt-2 text-sm">{files.length ? `已選擇 ${files.length} 個檔案` : "拖曳檔案到這裡，或點擊選擇檔案"}</strong><span className="mt-1 text-xs text-muted">{files.length ? files.map((file) => `${file.name}（${pretty(file.size)}）`).join("、") : "支援批次選取，單檔上限由管理員設定"}</span></label>
        <div className="mt-4 grid gap-3 sm:grid-cols-4"><Field label="目標大小"><div className="flex gap-2"><Input type="number" min="0.5" step="0.1" value={target} onChange={(e) => setTarget(e.target.value)} /><Select value={unit} onChange={(e) => setUnit(e.target.value)}><option>MB</option><option>KB</option></Select></div></Field><Field label="輸出格式" hint="選擇壓縮後檔案格式"><Select value={outputFormat} onChange={(e) => setOutputFormat(e.target.value)}><option value="original">自動最佳格式</option><option value="webp">WebP（圖片）</option><option value="jpeg">JPEG（圖片）</option><option value="avif">AVIF（圖片）</option><option value="pdf">PDF（僅 PDF）</option></Select></Field><Field label="壓縮模式"><Select value={mode} onChange={(e) => setMode(e.target.value)}><option value="precise">精準目標大小</option><option value="best">最佳品質</option><option value="fast">最快壓縮</option><option value="custom">自訂品質</option></Select></Field><div className="flex items-end"><Button full size="lg" onClick={submit} loading={busy}>開始智慧壓縮</Button></div></div>
        {warning && <p className="mt-3 rounded-xl border border-amber-300/30 bg-amber-300/10 p-3 text-xs text-amber-100">此目標大小可能造成文字、公式或細線品質明顯下降，系統會優先保護學習文件可讀性。</p>}
      </Card>
      <Card title="處理狀態" subtitle="真實階段狀態，不顯示虛假的處理百分比">
        {!job && !batch ? <div className="flex min-h-40 items-center justify-center text-sm text-muted">選擇檔案後開始，這裡會顯示進度。</div> : batch ? <div className="space-y-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">{batch.batchName}</p><p className="mt-1 text-xs text-muted">已完成 {batch.completed}/{batch.total} 個檔案</p></div><Badge tone={batch.progress >= 100 ? "green" : "cyan"}>{batch.progress >= 100 ? "批次完成" : "批次處理中"}</Badge></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#7c5cff] to-[#37d3ff] transition-all" style={{ width: `${batch.progress}%` }} /></div><div className="max-h-40 space-y-1 overflow-y-auto text-xs">{batch.jobs.map((item) => <div key={item.id} className="flex justify-between rounded-lg bg-white/5 px-2 py-1.5"><span className="truncate">{item.originalFilename}</span><span>{item.status}</span></div>)}</div>{batch.zipUrl && <Button full variant="gold" onClick={() => { window.open(batch.zipUrl!, "_blank", "noopener,noreferrer"); }}>一鍵下載 ZIP</Button>}</div> : <div className="space-y-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{job!.originalFilename}</p><p className="mt-1 text-xs text-muted">{stageText[job!.stage] ?? job!.stage}</p></div><Badge tone={job!.status === "failed" ? "rose" : job!.status.includes("completed") ? "green" : "cyan"}>{job!.status === "completed_with_warning" ? "完成但未達目標" : stageText[job!.stage] ?? job!.status}</Badge></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#7c5cff] to-[#37d3ff] transition-all" style={{ width: `${job!.progress}%` }} /></div>{job!.status === "failed" && <p className="rounded-xl border border-rose-300/30 bg-rose-300/10 p-3 text-xs text-rose-100">{job!.errorMessage}</p>}{job!.compressedSize && <div className="grid grid-cols-3 gap-2"><Stat label="壓縮後" value={pretty(job!.compressedSize)} tone="cyan" /><Stat label="節省" value={`${(job!.compressionRatio ?? 0).toFixed(1)}%`} tone="gold" /><Stat label="品質" value={job!.qualityScore ?? "—"} /></div>}{job!.resultUrl && <Button full variant="gold" onClick={() => { window.open(job!.resultUrl!, "_blank", "noopener,noreferrer"); }}>下載壓縮檔</Button>}</div>}
      </Card>
    </div>
    {job?.resultUrl && <Card title="壓縮後檔案預覽" subtitle="確認內容後再下載；預覽不會額外扣除使用額度"><div className="rounded-2xl border border-[var(--line)] bg-black/20 p-2">{job.mimeType === "application/pdf" || job.outputFormat === "pdf" ? <iframe src={job.resultUrl} title="壓縮後 PDF 預覽" className="h-[28rem] w-full rounded-xl bg-white" /> : <Image src={job.resultUrl} width={1200} height={760} unoptimized alt="壓縮後檔案預覽" className="max-h-[28rem] w-full rounded-xl object-contain" />}</div>{files[0] && <p className="mt-2 text-xs text-muted">原始檔案：{files[0].name} ・ 壓縮後：{pretty(job.compressedSize)} ・ 格式：{job.outputFormat ?? "自動最佳格式"}</p>}</Card>}
    {stats && <Card title="使用量統計" subtitle="最近 30 天的智慧壓縮使用情況"><div className="grid gap-3 sm:grid-cols-4"><Stat label="壓縮工作" value={stats.totalJobs} tone="cyan" /><Stat label="完成工作" value={stats.completedJobs} tone="violet" /><Stat label="處理原始檔" value={pretty(stats.totalOriginalBytes)} /><Stat label="平均節省" value={`${stats.averageSavedPercent.toFixed(1)}%`} tone="gold" /></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><p className="mb-2 text-xs text-muted">每日壓縮次數</p><BarChart series={stats.daily.map((item) => ({ label: item.label, value: item.value }))} suffix=" 次" /></div><div><p className="mb-2 text-xs text-muted">每日平均節省比例</p><LineChart series={stats.daily.map((item) => ({ label: item.label, value: item.value ? item.saved / item.value : 0 }))} suffix="%" color="#ffc857" /></div></div></Card>}
    <Card title="壓縮紀錄" subtitle="只顯示你的歷史紀錄" action={<Select value={filter} onChange={(e) => setFilter(e.target.value)} className="!w-auto"><option value="all">全部狀態</option><option value="completed">已完成</option><option value="processing">處理中</option><option value="failed">失敗</option></Select>}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs text-muted"><tr><th className="pb-3">檔案</th><th className="pb-3">原始大小</th><th className="pb-3">壓縮後</th><th className="pb-3">節省</th><th className="pb-3">狀態</th><th className="pb-3" /></tr></thead><tbody>{visibleHistory.map((item) => <tr key={item.id} className="border-t border-[var(--line)]"><td className="py-3">{item.originalFilename}</td><td>{pretty(item.originalSize)}</td><td>{pretty(item.compressedSize)}</td><td>{item.compressionRatio == null ? "—" : `${item.compressionRatio.toFixed(1)}%`}</td><td><Badge tone={item.status === "failed" ? "rose" : item.status.includes("completed") ? "green" : "cyan"}>{item.status}</Badge></td><td>{item.resultUrl && <a className="text-[#37d3ff] hover:underline" href={item.resultUrl} download>下載</a>}</td></tr>)}{!visibleHistory.length && <tr><td colSpan={6} className="py-8 text-center text-muted">沒有符合條件的紀錄</td></tr>}</tbody></table></div></Card>
  </main>;
}
