import { z } from "zod";
import { and, asc, desc, eq, gte, ilike, inArray, lte, or, sql } from "drizzle-orm";
import { db } from "@/db";
import { auditLogs, educationGrades, educationSchools, educationStages, educationSubjects, textbookContents, textbookEditions, textbookLessons, userSettings } from "@/db/schema";
import { route, type RouteDef } from "../router";
import { notFound } from "../core";
import { writeAudit } from "../audit";
import { putObject } from "../storage";
import { createFileContext } from "../unified-ai-engine";

const idSchema = z.string().uuid();
const stageScope = z.object({ stageId: idSchema.optional(), schoolId: idSchema.optional(), gradeId: idSchema.optional(), subjectId: idSchema.optional() });

export const routes: RouteDef[] = [
  route({ method: "GET", path: "/admin/audit-logs", auth: "admin", handler: async (ctx) => {
    const page = Math.max(1, Number(ctx.query.get("page") ?? 1) || 1); const pageSize = Math.min(100, Math.max(10, Number(ctx.query.get("pageSize") ?? 30) || 30));
    const userId = ctx.query.get("userId"); const eventType = ctx.query.get("eventType"); const moduleFilter = ctx.query.get("module"); const outcome = ctx.query.get("outcome"); const resourceId = ctx.query.get("resourceId"); const keyword = ctx.query.get("q")?.trim(); const from = ctx.query.get("from"); const to = ctx.query.get("to");
    const filters = [userId ? eq(auditLogs.userId, userId) : undefined, eventType ? eq(auditLogs.eventType, eventType) : undefined, moduleFilter ? eq(auditLogs.module, moduleFilter) : undefined, outcome ? eq(auditLogs.outcome, outcome) : undefined, resourceId ? eq(auditLogs.resourceId, resourceId) : undefined, from ? gte(auditLogs.occurredAt, new Date(from)) : undefined, to ? lte(auditLogs.occurredAt, new Date(to)) : undefined, keyword ? or(ilike(auditLogs.action, `%${keyword}%`), ilike(auditLogs.resourceId, `%${keyword}%`), ilike(auditLogs.errorCategory, `%${keyword}%`)) : undefined].filter(Boolean);
    const rows = await db.select().from(auditLogs).where(filters.length ? and(...filters) : undefined).orderBy(desc(auditLogs.occurredAt)).limit(pageSize).offset((page - 1) * pageSize);
    const [{ count }] = await db.select({ count: sql<number>`count(*)::int` }).from(auditLogs).where(filters.length ? and(...filters) : undefined);
    await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "audit", action: "audit_logs.view", resourceId: userId ?? "all", ip: ctx.ip, metadata: { status: 200, route: "/admin/audit-logs", method: "GET", targetCount: rows.length } });
    return { logs: rows, page, pageSize, total: count ?? 0, totalPages: Math.ceil((count ?? 0) / pageSize) };
  }}),
  route({ method: "GET", path: "/admin/audit-logs/:userId/timeline", auth: "admin", handler: async (ctx) => {
    const rows = await db.select().from(auditLogs).where(eq(auditLogs.userId, ctx.params.userId)).orderBy(desc(auditLogs.occurredAt)).limit(200);
    await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "audit", action: "audit_timeline.view", resourceId: ctx.params.userId, ip: ctx.ip, metadata: { status: 200, route: "/admin/audit-logs/:userId/timeline", method: "GET", targetCount: rows.length } });
    return { logs: rows };
  }}),
  route({ method: "GET", path: "/education/options", auth: "user", handler: async () => ({ stages: await db.select().from(educationStages).where(eq(educationStages.enabled, true)).orderBy(asc(educationStages.sortOrder)), schools: await db.select().from(educationSchools).where(eq(educationSchools.enabled, true)).orderBy(asc(educationSchools.sortOrder)), grades: await db.select().from(educationGrades).where(eq(educationGrades.enabled, true)).orderBy(asc(educationGrades.sortOrder)), subjects: await db.select().from(educationSubjects).where(eq(educationSubjects.enabled, true)).orderBy(asc(educationSubjects.sortOrder)) }) }),
  route({ method: "GET", path: "/textbooks", auth: "user", handler: async (ctx) => {
    const q = ctx.query.get("q")?.trim(); const scope = stageScope.safeParse(Object.fromEntries(["stageId", "schoolId", "gradeId", "subjectId"].map(k => [k, ctx.query.get(k) || undefined]))).data ?? {};
    const filters = [eq(textbookEditions.enabled, true), scope.stageId ? eq(textbookEditions.stageId, scope.stageId) : undefined, scope.schoolId ? eq(textbookEditions.schoolId, scope.schoolId) : undefined, scope.gradeId ? eq(textbookEditions.gradeId, scope.gradeId) : undefined, scope.subjectId ? eq(textbookEditions.subjectId, scope.subjectId) : undefined, q ? or(ilike(textbookEditions.publisher, `%${q}%`), ilike(textbookEditions.version, `%${q}%`), ilike(textbookEditions.volume, `%${q}%`)) : undefined].filter(Boolean);
    const rows = await db.select({ edition: textbookEditions }).from(textbookEditions).innerJoin(educationStages, eq(educationStages.id, textbookEditions.stageId)).innerJoin(userSettings, eq(userSettings.schoolLevel, educationStages.key)).where(and(...filters, eq(userSettings.userId, ctx.user!.userId))).orderBy(asc(textbookEditions.sortOrder), desc(textbookEditions.createdAt));
    return { editions: rows.map((row) => row.edition) };
  }}),
  route({ method: "GET", path: "/textbooks/:id", auth: "user", handler: async (ctx) => { const edition = (await db.select({ edition: textbookEditions }).from(textbookEditions).innerJoin(educationStages, eq(educationStages.id, textbookEditions.stageId)).innerJoin(userSettings, eq(userSettings.schoolLevel, educationStages.key)).where(and(eq(textbookEditions.id, ctx.params.id), eq(textbookEditions.enabled, true), eq(userSettings.userId, ctx.user!.userId))).limit(1))[0]?.edition; if (!edition) throw notFound("找不到符合目前教育階段的教材版本"); const lessons = await db.select().from(textbookLessons).where(and(eq(textbookLessons.editionId, edition.id), eq(textbookLessons.enabled, true))).orderBy(asc(textbookLessons.sortOrder)); const contents = lessons.length ? await db.select().from(textbookContents).where(and(inArray(textbookContents.lessonId, lessons.map(l => l.id)), eq(textbookContents.enabled, true))).orderBy(asc(textbookContents.sortOrder)) : []; return { edition, lessons: lessons.map(l => ({ ...l, contents: contents.filter(c => c.lessonId === l.id) })) }; } }),
  route({ method: "GET", path: "/admin/textbooks", auth: "admin", handler: async () => ({ editions: await db.select().from(textbookEditions).orderBy(asc(textbookEditions.sortOrder), desc(textbookEditions.createdAt)) }) }),
  route({ method: "POST", path: "/admin/textbooks", auth: "admin", handler: async (ctx) => { const body = await ctx.json(z.object({ ...stageScope.shape, publisher: z.string().min(1).max(120), version: z.string().max(120).default(""), volume: z.string().max(80).default(""), coverUrl: z.string().url().or(z.literal("/brand/studynova-logo-square.png")).default("/brand/studynova-logo-square.png"), description: z.string().max(2000).default(""), isbn: z.string().max(80).default(""), sortOrder: z.number().int().default(0) })); const row = (await db.insert(textbookEditions).values(body).returning())[0]; await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "edition.create", resourceId: row.id, ip: ctx.ip }); return { edition: row }; } }),
  route({ method: "PATCH", path: "/admin/textbooks/:id", auth: "admin", handler: async (ctx) => { const body = await ctx.json(z.object({ publisher: z.string().min(1).max(120).optional(), version: z.string().max(120).optional(), volume: z.string().max(80).optional(), coverUrl: z.string().max(500).optional(), description: z.string().max(2000).optional(), isbn: z.string().max(80).optional(), metadata: z.record(z.string(), z.unknown()).optional(), ocrStatus: z.string().max(40).optional(), enabled: z.boolean().optional(), sortOrder: z.number().int().optional() })); const rows = await db.update(textbookEditions).set({ ...body, updatedAt: new Date() }).where(eq(textbookEditions.id, ctx.params.id)).returning(); if (!rows[0]) throw notFound("找不到教材版本"); await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "edition.update", resourceId: ctx.params.id, ip: ctx.ip }); return { edition: rows[0] }; } }),
  route({ method: "POST", path: "/admin/textbooks/:id/ocr", auth: "admin", handler: async (ctx) => { const admin = ctx.requireUser(); const edition = (await db.select().from(textbookEditions).where(eq(textbookEditions.id, ctx.params.id)).limit(1))[0]; if (!edition) throw notFound("找不到教材版本"); const form = await ctx.formData(); const files = form.getAll("files").filter((value): value is File => typeof File !== "undefined" && value instanceof File); if (!files.length) throw new Error("請上傳教材圖片或 PDF"); await db.update(textbookEditions).set({ ocrStatus: "analyzing", updatedAt: new Date() }).where(eq(textbookEditions.id, edition.id)); const results = []; for (const file of files.slice(0, 8)) { const stored = await putObject({ userId: admin.userId, filename: file.name, mimeType: file.type || "image/jpeg", data: Buffer.from(await file.arrayBuffer()), allow: ["image", "pdf"] }); results.push(await createFileContext({ userId: admin.userId, objectId: stored.id, originalName: file.name, batch: Date.now(), scope: { includeQuestion: true, includeHandwriting: true, includeNote: true, highlightPriority: true } })); } const lesson = (await db.insert(textbookLessons).values({ editionId: edition.id, title: `OCR 匯入 ${new Date().toLocaleDateString("zh-TW")}`, description: "由 StudyNova OCR 分析匯入，可再由管理員編輯。", sortOrder: 999 }).returning())[0]; let imported = 0; for (const result of results) { const segments = result.context.detected as Array<{ kind?: string; text?: string; confidence?: number }>; for (const segment of segments) { if (!segment.text?.trim()) continue; await db.insert(textbookContents).values({ lessonId: lesson.id, type: segment.kind?.toLowerCase() || "note", title: `${segment.kind || "OCR"} ${imported + 1}`, body: segment.text, metadata: { confidence: segment.confidence ?? 0, source: result.context.originalName, ocr: true } }); imported += 1; } } await db.update(textbookEditions).set({ ocrStatus: "ready", updatedAt: new Date() }).where(eq(textbookEditions.id, edition.id)); await writeAudit({ userId: admin.userId, eventType: "admin_operation", module: "textbooks", action: "edition.ocr_import", resourceId: edition.id, ip: ctx.ip, metadata: { files: files.length, imported } }); return { lesson, imported, files: results.map((result) => result.context) }; } }),
  route({ method: "DELETE", path: "/admin/textbooks/:id", auth: "admin", handler: async (ctx) => { const rows = await db.update(textbookEditions).set({ enabled: false, updatedAt: new Date() }).where(eq(textbookEditions.id, ctx.params.id)).returning({ id: textbookEditions.id }); if (!rows[0]) throw notFound("找不到教材版本"); await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "edition.disable", resourceId: ctx.params.id, ip: ctx.ip }); return { disabled: true }; } }),
  route({ method: "POST", path: "/admin/textbooks/:id/lessons", auth: "admin", handler: async (ctx) => { const body = await ctx.json(z.object({ title: z.string().min(1).max(160), description: z.string().max(1000).default(""), sortOrder: z.number().int().default(0) })); const row = (await db.insert(textbookLessons).values({ ...body, editionId: ctx.params.id }).returning())[0]; await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "lesson.create", resourceId: row.id, ip: ctx.ip }); return { lesson: row }; } }),
  route({ method: "POST", path: "/admin/textbook-lessons/:id/contents", auth: "admin", handler: async (ctx) => { const body = await ctx.json(z.object({ type: z.string().min(1).max(80), title: z.string().min(1).max(160), body: z.string().max(20000), metadata: z.record(z.string(), z.unknown()).default({}), sortOrder: z.number().int().default(0) })); const row = (await db.insert(textbookContents).values({ ...body, lessonId: ctx.params.id }).returning())[0]; await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "content.create", resourceId: row.id, ip: ctx.ip }); return { content: row }; } }),
  route({ method: "PATCH", path: "/admin/textbook-lessons/:id", auth: "admin", handler: async (ctx) => { const body = await ctx.json(z.object({ title: z.string().min(1).max(160).optional(), description: z.string().max(1000).optional(), sortOrder: z.number().int().optional(), enabled: z.boolean().optional() })); const rows = await db.update(textbookLessons).set({ ...body, updatedAt: new Date() }).where(eq(textbookLessons.id, ctx.params.id)).returning(); if (!rows[0]) throw notFound("找不到課次"); await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "lesson.update", resourceId: ctx.params.id, ip: ctx.ip }); return { lesson: rows[0] }; } }),
  route({ method: "DELETE", path: "/admin/textbook-lessons/:id", auth: "admin", handler: async (ctx) => { const rows = await db.update(textbookLessons).set({ enabled: false, updatedAt: new Date() }).where(eq(textbookLessons.id, ctx.params.id)).returning({ id: textbookLessons.id }); if (!rows[0]) throw notFound("找不到課次"); await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "lesson.disable", resourceId: ctx.params.id, ip: ctx.ip }); return { disabled: true }; } }),
  route({ method: "PATCH", path: "/admin/textbook-contents/:id", auth: "admin", handler: async (ctx) => { const body = await ctx.json(z.object({ type: z.string().min(1).max(80).optional(), title: z.string().min(1).max(160).optional(), body: z.string().max(20000).optional(), metadata: z.record(z.string(), z.unknown()).optional(), sortOrder: z.number().int().optional(), enabled: z.boolean().optional() })); const rows = await db.update(textbookContents).set({ ...body, updatedAt: new Date() }).where(eq(textbookContents.id, ctx.params.id)).returning(); if (!rows[0]) throw notFound("找不到教材內容"); await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "content.update", resourceId: ctx.params.id, ip: ctx.ip }); return { content: rows[0] }; } }),
  route({ method: "DELETE", path: "/admin/textbook-contents/:id", auth: "admin", handler: async (ctx) => { const rows = await db.update(textbookContents).set({ enabled: false, updatedAt: new Date() }).where(eq(textbookContents.id, ctx.params.id)).returning({ id: textbookContents.id }); if (!rows[0]) throw notFound("找不到教材內容"); await writeAudit({ userId: ctx.user?.userId, eventType: "admin_operation", module: "textbooks", action: "content.disable", resourceId: ctx.params.id, ip: ctx.ip }); return { disabled: true }; } }),
];
