import { and, desc, eq, gte, lte } from "drizzle-orm";
import { Document, Packer, Paragraph, TextRun } from "docx";
import ExcelJS from "exceljs";
import { PDFDocument, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import JSZip from "jszip";
import { db } from "@/db";
import { dailyTasks, focusSessions, notes, novaTransactions, platformSettings, studyMaterials, studyPlans, studyRecords, tasks, userAchievements, userVocabularies, wrongQuestions, xpTransactions } from "@/db/schema";
import { route, type RouteDef } from "../router";
import { grantNova, isProUser } from "../economy";

const DATASETS = {
  notes: { label: "我的專屬筆記", table: notes },
  vocabulary: { label: "我的單字", table: userVocabularies },
  wrong: { label: "錯題本", table: wrongQuestions },
  studyMaterials: { label: "學習資料與 AI 摘要", table: studyMaterials },
  plans: { label: "個人學習計畫", table: studyPlans },
  studyRecords: { label: "每日學習紀錄", table: studyRecords },
  focus: { label: "專注計時紀錄", table: focusSessions },
  tasks: { label: "任務完成紀錄", table: tasks },
  dailyTasks: { label: "每日任務", table: dailyTasks },
  achievements: { label: "成就與徽章", table: userAchievements },
  nova: { label: "Nova 交易紀錄", table: novaTransactions },
  xp: { label: "XP 紀錄", table: xpTransactions },
} as const;
type Kind = keyof typeof DATASETS;
type Format = "json" | "csv" | "txt" | "md" | "pdf" | "docx" | "xlsx" | "zip";
const KINDS = Object.keys(DATASETS) as Kind[];
const FORMATS = ["json", "csv", "txt", "md", "pdf", "docx", "xlsx", "zip"] as Format[];
const DEFAULT_COSTS: Record<Format, number> = { json: 100, csv: 200, txt: 100, md: 100, pdf: 800, docx: 600, xlsx: 500, zip: 1000 };
type ExportPolicy = { enabled: boolean; proOnly: boolean; allowedKinds: Kind[]; allowedFormats: Format[]; freeFormats: Format[]; freeUntil: string | null; costs: Partial<Record<Format, number>>; minimumNova: number };

async function getExportPolicy(): Promise<ExportPolicy> {
  const row = (await db.select({ value: platformSettings.value }).from(platformSettings).where(eq(platformSettings.key, "learning_exports")).limit(1))[0];
  const value = (row?.value ?? {}) as Record<string, unknown>;
  const list = <T extends string>(input: unknown, fallback: T[], valid: T[]) => Array.isArray(input) ? input.filter((item): item is T => typeof item === "string" && valid.includes(item as T)) : fallback;
  const allowedKinds = list(value.allowedKinds, KINDS, KINDS);
  const allowedFormats = list(value.allowedFormats, FORMATS, FORMATS);
  const freeFormats = list(value.freeFormats, [], FORMATS);
  const rawCosts = value.costs && typeof value.costs === "object" ? value.costs as Record<string, unknown> : {};
  const costs = Object.fromEntries(FORMATS.map((format) => [format, Number.isFinite(Number(rawCosts[format])) ? Math.max(0, Math.floor(Number(rawCosts[format]))) : DEFAULT_COSTS[format]])) as Partial<Record<Format, number>>;
  const freeUntil = typeof value.freeUntil === "string" && !Number.isNaN(Date.parse(value.freeUntil)) ? value.freeUntil : null;
  return { enabled: value.enabled !== false, proOnly: value.proOnly === true, allowedKinds, allowedFormats, freeFormats, freeUntil, costs, minimumNova: Math.max(0, Number(value.minimumNova ?? 0)) };
}
async function enforcePolicy(userId: string, kinds: Kind[], format: Format) {
  const policy = await getExportPolicy();
  if (!policy.enabled) throw new Error("目前尚未開放資料匯出");
  if (policy.proOnly && !(await isProUser(userId))) throw new Error("資料匯出目前僅開放 Nova Pro 使用者");
  if (kinds.some((kind) => !policy.allowedKinds.includes(kind))) throw new Error("你選擇的資料類型目前未開放匯出");
  if (!policy.allowedFormats.includes(format)) throw new Error("你選擇的匯出格式目前未開放");
  const freeActive = policy.freeFormats.includes(format) && (!policy.freeUntil || new Date(policy.freeUntil).getTime() > Date.now());
  const cost = freeActive ? 0 : policy.costs[format] ?? DEFAULT_COSTS[format];
  return { policy, cost };
}
function safeKind(value: string): Kind[] { return value === "all" ? KINDS : value.split(",").filter((item): item is Kind => KINDS.includes(item as Kind)); }
function jsonSafe(value: unknown): unknown { if (value instanceof Date) return value.toISOString(); if (Array.isArray(value)) return value.map(jsonSafe); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, jsonSafe(item)])); return value; }
function textValue(value: unknown, fallback = "尚未補充") { const text = typeof value === "string" ? value.trim() : value === null || value === undefined ? "" : String(value); return text || fallback; }
function wordValue(row: Record<string, unknown>, key: string, fallback = "尚未補充") {
  const direct = row[key];
  if (direct !== null && direct !== undefined && String(direct).trim()) return textValue(direct, fallback);
  const analysis = row.analysis && typeof row.analysis === "object" ? row.analysis as Record<string, unknown> : null;
  return textValue(analysis?.[key], fallback);
}
function isVocabularyRow(row: Record<string, unknown>) { return row.dataset === "vocabulary"; }
function readableRow(row: Record<string, unknown>, index: number) {
  if (isVocabularyRow(row)) return [`${index + 1}. ${wordValue(row, "word", "未命名單字")}`, `詞性：${wordValue(row, "partOfSpeech", "未標示")}`, `音標：${wordValue(row, "phonetic", "未標示")}`, `中文意思：${wordValue(row, "meaning")}`, `例句：${wordValue(row, "example")}`, `例句翻譯：${wordValue(row, "exampleZh")}`];
  const label = textValue(row.datasetLabel ?? row.dataset, "資料");
  return [`${index + 1}. ${label}`, ...Object.entries(row).filter(([key]) => !["dataset", "datasetLabel", "id", "userId", "analysis"].includes(key)).map(([key, value]) => `${key}：${typeof value === "object" ? JSON.stringify(jsonSafe(value)) : textValue(value, "")}`)];
}
function rowsToCsv(rows: Array<Record<string, unknown>>) { const vocabulary = rows.length > 0 && rows.every(isVocabularyRow); const output: Array<Record<string, unknown>> = vocabulary ? rows.map((row, index) => ({ 項次: index + 1, 單字: wordValue(row, "word", ""), 詞性: wordValue(row, "partOfSpeech", ""), 音標: wordValue(row, "phonetic", ""), 中文意思: wordValue(row, "meaning", ""), 英文例句: wordValue(row, "example", ""), 例句翻譯: wordValue(row, "exampleZh", "") })) : rows; const keys = Array.from(new Set(output.flatMap((row) => Object.keys(row)))); const quote = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; return `\uFEFF${keys.map(quote).join(",")}\n${output.map((row) => keys.map((key) => quote(typeof row[key] === "object" ? JSON.stringify(jsonSafe(row[key])) : row[key])).join(",")).join("\n")}`; }
function rowsToText(rows: Array<Record<string, unknown>>, markdown = false) { return rows.map((row, index) => { const lines = readableRow(row, index); return markdown ? lines.map((line, lineIndex) => lineIndex === 0 ? `## ${line}` : `- ${line}`).join("\n") : lines.join("\n"); }).join("\n\n"); }
async function loadRows(kind: Kind, userId: string, from?: string, to?: string) { const table = DATASETS[kind].table as typeof notes; const conditions = [eq(table.userId, userId)]; if (from && "createdAt" in table) conditions.push(gte(table.createdAt, new Date(from)) as never); if (to && "createdAt" in table) conditions.push(lte(table.createdAt, new Date(to)) as never); return (await db.select().from(table).where(and(...conditions)).orderBy(desc(table.createdAt)).limit(10000)).map((row) => jsonSafe(row) as Record<string, unknown>); }
function wrapText(text: string, font: PDFFont, size: number, maxWidth: number) { const lines: string[] = []; let current = ""; for (const char of text) { const next = current + char; if (current && font.widthOfTextAtSize(next, size) > maxWidth) { lines.push(current); current = char; } else current = next; } if (current) lines.push(current); return lines.length ? lines : [""]; }
function drawLine(page: PDFPage, font: PDFFont, text: string, x: number, y: number, size: number, maxWidth: number, color = rgb(0.13, 0.16, 0.22)) { for (const line of wrapText(text, font, size, maxWidth)) { page.drawText(line, { x, y, size, font, color }); y -= size + 4; } return y; }
async function embedCjkFont(pdf: PDFDocument) { return (await import("../cjk-font")).embedCjkFont(pdf); }
async function renderPdf(rows: Array<Record<string, unknown>>, title: string) { const pdf = await PDFDocument.create(); const font = await embedCjkFont(pdf); const bold = font; let page = pdf.addPage([595, 842]); let y = 795; const margin = 42; const width = 511; const newPage = () => { page = pdf.addPage([595, 842]); y = 795; page.drawText("StudyNova 單字書／學習資料", { x: margin, y, size: 9, font: bold, color: rgb(0.25, 0.38, 0.5) }); y -= 28; }; page.drawText(title, { x: margin, y, size: 20, font: bold, color: rgb(0.08, 0.24, 0.4) }); y -= 28; page.drawText(`共 ${rows.length} 筆　・　產生日期 ${new Date().toLocaleDateString("zh-TW")}`, { x: margin, y, size: 9, font, color: rgb(0.35, 0.4, 0.46) }); y -= 28; for (let index = 0; index < rows.length; index += 1) { const lines = readableRow(rows[index], index); const needed = lines.length * 16 + 26; if (y < 60 + needed) newPage(); page.drawRectangle({ x: margin - 8, y: y - needed + 8, width, height: needed, color: rgb(index % 2 ? 0.97 : 0.94, index % 2 ? 0.98 : 0.96, 1), borderColor: rgb(0.78, 0.84, 0.9), borderWidth: 0.6 }); let lineY = y - 2; lines.forEach((line, lineIndex) => { lineY = drawLine(page, font, line, margin, lineY, lineIndex === 0 ? 13 : 9.5, width - 16, lineIndex === 0 ? rgb(0.05, 0.22, 0.38) : rgb(0.18, 0.22, 0.28)); }); y -= needed + 10; } return Buffer.from(await pdf.save()); }
async function renderDocx(rows: Array<Record<string, unknown>>, title: string) { const children = [new Paragraph({ children: [new TextRun({ text: title, bold: true, size: 30 })] }), ...rows.flatMap((row, index) => readableRow(row, index).map((line, lineIndex) => new Paragraph({ children: [new TextRun({ text: line, bold: lineIndex === 0, size: lineIndex === 0 ? 24 : 20 })] })))]; return Packer.toBuffer(new Document({ sections: [{ children }] })); }
async function renderXlsx(rows: Array<Record<string, unknown>>, title: string) { const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet(title.slice(0, 28)); const vocabulary = rows.length > 0 && rows.every(isVocabularyRow); const output = vocabulary ? rows.map((row, index) => ({ 項次: index + 1, 單字: wordValue(row, "word", ""), 詞性: wordValue(row, "partOfSpeech", ""), 音標: wordValue(row, "phonetic", ""), 中文意思: wordValue(row, "meaning", ""), 英文例句: wordValue(row, "example", ""), 例句翻譯: wordValue(row, "exampleZh", "") })) : rows.map((row) => Object.fromEntries(Object.entries(row).filter(([key]) => !["id", "userId", "analysis"].includes(key)))); const keys = Array.from(new Set(output.flatMap((row) => Object.keys(row)))); sheet.addRow(keys); output.forEach((row) => sheet.addRow(keys.map((key) => typeof row[key] === "object" ? JSON.stringify(row[key]) : row[key]))); sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; sheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF245A78" } }; sheet.columns.forEach((column) => { column.width = 22; }); return Buffer.from(await workbook.xlsx.writeBuffer()); }
async function renderBinary(rows: Array<Record<string, unknown>>, format: Exclude<Format, "json" | "csv" | "txt" | "md" | "zip">, title: string) { if (format === "pdf") return renderPdf(rows, title); if (format === "docx") return renderDocx(rows, title); return renderXlsx(rows, title); }
function attachment(data: string | Buffer, filename: string, type: string) { return new Response(typeof data === "string" ? data : (new Uint8Array(data) as unknown as BodyInit), { headers: { "content-type": `${type}; charset=utf-8`, "content-disposition": `attachment; filename="${filename}"` } }); }
export const routes: RouteDef[] = [
  route({ method: "GET", path: "/exports/policy", auth: "user", handler: async (ctx) => { const user = ctx.requireUser(); const policy = await getExportPolicy(); return { enabled: policy.enabled, proOnly: policy.proOnly, isPro: await isProUser(user.userId), allowedKinds: policy.allowedKinds, allowedFormats: policy.allowedFormats, freeFormats: policy.freeFormats, freeUntil: policy.freeUntil, costs: policy.costs }; } }),
  route({ method: "GET", path: "/exports/preview", auth: "user", handler: async (ctx) => { const user = ctx.requireUser(); const kinds = safeKind(ctx.query.get("kind") ?? "all"); const format = (ctx.query.get("format") ?? "json") as Format; if (!kinds.length) return { datasets: [], total: 0, estimatedBytes: 0, cost: 0, sample: [] }; const { policy, cost } = await enforcePolicy(user.userId, kinds, format); const rows = await Promise.all(kinds.map((kind) => loadRows(kind, user.userId, ctx.query.get("from") ?? undefined, ctx.query.get("to") ?? undefined))); return { datasets: kinds.map((kind, index) => ({ kind, label: DATASETS[kind].label, count: rows[index].length })), total: rows.reduce((sum, item) => sum + item.length, 0), estimatedBytes: rows.reduce((sum, item) => sum + JSON.stringify(item).length, 0), sample: rows.flatMap((items, index) => items.slice(0, 2).map((row) => ({ dataset: DATASETS[kinds[index]].label, ...row }))).slice(0, 6), cost, free: cost === 0, policy: { allowedKinds: policy.allowedKinds, allowedFormats: policy.allowedFormats } }; } }),
  route({ method: "GET", path: "/exports/preview-file", auth: "user", handler: async (ctx) => { const user = ctx.requireUser(); const kinds = safeKind(ctx.query.get("kind") ?? "all"); const format = (ctx.query.get("format") ?? "pdf") as Format; if (!kinds.length || !FORMATS.includes(format)) throw new Error("預覽格式無效"); await enforcePolicy(user.userId, kinds, format); const from = ctx.query.get("from") ?? undefined; const to = ctx.query.get("to") ?? undefined; const loaded = await Promise.all(kinds.map(async (kind) => ({ kind, label: DATASETS[kind].label, rows: await loadRows(kind, user.userId, from, to) }))); const rows = loaded.flatMap((item) => item.rows.map((row) => ({ dataset: item.kind, datasetLabel: item.label, ...row }))); if (format === "json") return new Response(JSON.stringify({ version: 1, datasets: loaded }, null, 2), { headers: { "content-type": "application/json; charset=utf-8", "content-disposition": "inline" } }); if (format === "csv") return new Response(rowsToCsv(rows), { headers: { "content-type": "text/csv; charset=utf-8", "content-disposition": "inline" } }); if (format === "txt" || format === "md") return new Response(rowsToText(rows, format === "md"), { headers: { "content-type": format === "md" ? "text/markdown; charset=utf-8" : "text/plain; charset=utf-8", "content-disposition": "inline" } }); const data = await renderBinary(rows, format as "pdf" | "docx" | "xlsx", "StudyNova 學習資料匯出"); const type = format === "pdf" ? "application/pdf" : format === "docx" ? "application/vnd.openxmlformats-officedocument.wordprocessingml.document" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"; return new Response(new Uint8Array(data) as unknown as BodyInit, { headers: { "content-type": type, "content-disposition": "inline" } }); } }),
  route({ method: "GET", path: "/exports/download", auth: "user", rate: { limit: 10, windowSec: 3600 }, handler: async (ctx) => { const user = ctx.requireUser(); const kinds = safeKind(ctx.query.get("kind") ?? "all"); const format = (ctx.query.get("format") ?? "json") as Format; if (!kinds.length || !FORMATS.includes(format)) throw new Error("匯出資料類型或格式無效"); if (ctx.query.get("confirmed") !== "1") throw new Error("請先完成兩次匯出確認"); const { cost } = await enforcePolicy(user.userId, kinds, format); if (cost > 0) await grantNova({ userId: user.userId, amount: -cost, reason: `資料匯出：${format.toUpperCase()}`, source: "export", idempotencyKey: `export:${user.userId}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}` }); const from = ctx.query.get("from") ?? undefined; const to = ctx.query.get("to") ?? undefined; const loaded = await Promise.all(kinds.map(async (kind) => ({ kind, label: DATASETS[kind].label, rows: await loadRows(kind, user.userId, from, to) }))); const stamp = new Date().toISOString().slice(0, 10); if (format === "zip") { const zip = new JSZip(); zip.file("README.txt", `StudyNova 個人資料匯出\n匯出日期：${new Date().toISOString()}\n只包含目前登入使用者自己的資料。`); for (const item of loaded) zip.file(`${item.kind}.json`, JSON.stringify({ label: item.label, rows: item.rows }, null, 2)); return attachment(Buffer.from(await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" })), `StudyNova_Export_${stamp}.zip`, "application/zip"); } const rows = loaded.flatMap((item) => item.rows.map((row) => ({ dataset: item.kind, datasetLabel: item.label, ...row }))); if (format === "json") return attachment(JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), datasets: loaded }, null, 2), `StudyNova_Export_${stamp}.json`, "application/json"); if (format === "csv") return attachment(rowsToCsv(rows), `StudyNova_Export_${stamp}.csv`, "text/csv"); if (format === "txt" || format === "md") return attachment(rowsToText(rows, format === "md"), `StudyNova_Export_${stamp}.${format}`, format === "md" ? "text/markdown" : "text/plain"); const data = await renderBinary(rows, format as "pdf" | "docx" | "xlsx", "StudyNova 學習資料匯出"); return new Response(new Uint8Array(data) as unknown as BodyInit, { headers: { "content-type": format === "pdf" ? "application/pdf" : format === "docx" ? "application/vnd.openxmlformats-officedocument.wordprocessingml.document" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "content-disposition": `attachment; filename="StudyNova_Export_${stamp}.${format}"` } }); } }),
];
