"use client";
import { useState } from "react";
import { apiDelete, apiPatch, apiPost, errorMessage, useApi } from "@/lib/api";
import { Badge, Button, Card, EmptyState, Field, Input, Select, Skeleton, Textarea, useToast } from "@/components/ui";

type Item = { id: string; title: string; content: string; detail: string; subject: string; topic: string; source: string; sourceUrl: string; status: string; scheduledDate: string | null; verifiedAt: string | null; verificationNote: string; coreConcept: string; };
const subjects = ["國文", "英文", "數學", "自然", "歷史", "地理", "公民", "物理", "化學", "生物", "地球科學", "隨機"];

export default function AdminDailyKnowledgePage() {
  const toast = useToast();
  const list = useApi<{ items: Item[]; subjects: string[] }>("/admin/daily-knowledge");
  const [subject, setSubject] = useState("隨機"); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [selected, setSelected] = useState<Item | null>(null); const [busy, setBusy] = useState(false);
  async function generate() { setBusy(true); try { await apiPost("/admin/daily-knowledge/generate", { subject, date }); await list.reload(); toast.push("success", "已建立每日知識草稿並完成來源／相似度檢查"); } catch (err) { toast.push("error", errorMessage(err)); } finally { setBusy(false); } }
  async function save(status?: Item["status"]) { if (!selected) return; try { const result = await apiPatch<{ item: Item }>(`/admin/daily-knowledge/${selected.id}`, { title: selected.title, content: selected.content, detail: selected.detail, subject: selected.subject, topic: selected.topic, source: selected.source, sourceUrl: selected.sourceUrl, coreConcept: selected.coreConcept, scheduledDate: selected.scheduledDate, status }); setSelected(result.item); await list.reload(); toast.push("success", status === "published" ? "每日知識已發布" : "內容已儲存"); } catch (err) { toast.push("error", errorMessage(err)); } }
  async function verify() { if (!selected) return; try { const result = await apiPost<{ item: Item }>(`/admin/daily-knowledge/${selected.id}/verify`); setSelected(result.item); await list.reload(); toast.push("success", result.item.status === "approved" ? "來源驗證通過" : "來源仍未完成驗證"); } catch (err) { toast.push("error", errorMessage(err)); } }
  async function archive() { if (!selected || !confirm("封存這則每日知識？封存後學生端不會再看到。")) return; try { await apiDelete(`/admin/daily-knowledge/${selected.id}`); setSelected(null); await list.reload(); toast.push("success", "已封存"); } catch (err) { toast.push("error", errorMessage(err)); } }
  return <div className="space-y-4"><header><p className="text-xs uppercase tracking-[0.2em] text-[#37d3ff]">Content Governance / Daily Knowledge</p><h1 className="mt-1 text-2xl font-semibold">每日知識</h1><p className="text-sm text-muted">AI 只建立草稿。來源無法驗證或內容與既有知識過度相似時，不會自動提供給學生。</p></header>
    <Card title="建立每日知識"><div className="grid gap-3 sm:grid-cols-3"><Field label="科目"><Select value={subject} onChange={(e) => setSubject(e.target.value)}>{subjects.map((value) => <option key={value}>{value}</option>)}</Select></Field><Field label="指定日期"><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field><div className="self-end"><Button disabled={busy} onClick={() => void generate()}>{busy ? "生成與驗證中…" : "AI 生成草稿"}</Button></div></div></Card>
    <Card title="內容清單"><div className="space-y-2">{list.loading && <Skeleton lines={5} />}{!list.loading && !list.data?.items.length && <EmptyState title="尚無每日知識" hint="建立第一則內容後，它會先經過來源驗證與相似度檢查。" />}{list.data?.items.map((item) => <button key={item.id} type="button" onClick={() => setSelected(item)} className={`glass-soft flex w-full items-center justify-between gap-3 rounded-xl p-3 text-left ${selected?.id === item.id ? "border-[#37d3ff]" : ""}`}><span className="min-w-0"><span className="block truncate font-semibold">{item.title}</span><span className="text-xs text-muted">{item.subject}・{item.scheduledDate ?? "未排程"}</span></span><Badge tone={item.status === "published" ? "green" : item.status === "approved" ? "cyan" : item.status === "rejected" ? "rose" : "muted"}>{item.status}</Badge></button>)}</div></Card>
    {selected && <Card title="編輯、驗證與發布" subtitle={`來源：${selected.source || "未填寫"}；${selected.verificationNote || "尚未驗證"}`}><div className="grid gap-3 sm:grid-cols-2"><Field label="標題"><Input value={selected.title} onChange={(e) => setSelected({ ...selected, title: e.target.value })} /></Field><Field label="科目"><Select value={selected.subject} onChange={(e) => setSelected({ ...selected, subject: e.target.value })}>{subjects.filter((value) => value !== "隨機").map((value) => <option key={value}>{value}</option>)}</Select></Field><Field label="主題"><Input value={selected.topic} onChange={(e) => setSelected({ ...selected, topic: e.target.value })} /></Field><Field label="指定日期"><Input type="date" value={selected.scheduledDate ?? ""} onChange={(e) => setSelected({ ...selected, scheduledDate: e.target.value || null })} /></Field><Field label="來源名稱"><Input value={selected.source} onChange={(e) => setSelected({ ...selected, source: e.target.value })} /></Field><Field label="來源網址"><Input value={selected.sourceUrl} onChange={(e) => setSelected({ ...selected, sourceUrl: e.target.value })} /></Field><Field label="核心概念"><Input value={selected.coreConcept} onChange={(e) => setSelected({ ...selected, coreConcept: e.target.value })} /></Field><div /><Field label="內容"><Textarea className="min-h-[160px]" value={selected.content} onChange={(e) => setSelected({ ...selected, content: e.target.value })} /></Field><Field label="詳細解析"><Textarea className="min-h-[160px]" value={selected.detail} onChange={(e) => setSelected({ ...selected, detail: e.target.value })} /></Field></div><div className="mt-3 flex flex-wrap gap-2"><Button onClick={() => void save()}>儲存修改</Button><Button variant="outline" onClick={() => void verify()}>重新驗證來源</Button><Button variant="outline" disabled={selected.status !== "approved" && selected.status !== "published"} onClick={() => void save("published")}>發布給學生</Button><Button variant="ghost" onClick={() => void archive()}>封存</Button></div></Card>}
  </div>;
}
